var dir_96ec55ea8c6b0b81e781b835d58b74fb =
[
    [ "Effects", "dir_a084b5da13925dcfc911abaf7d476c5b.html", "dir_a084b5da13925dcfc911abaf7d476c5b" ],
    [ "ControllerPoint.cs", "_controller_point_8cs.html", "_controller_point_8cs" ],
    [ "ControllerPointMouseWheelEventArgs.cs", "_controller_point_mouse_wheel_event_args_8cs.html", "_controller_point_mouse_wheel_event_args_8cs" ],
    [ "ControllPointDragEndEventArgs.cs", "_controll_point_drag_end_event_args_8cs.html", "_controll_point_drag_end_event_args_8cs" ],
    [ "ControllPointDragStartEventArgs.cs", "_controll_point_drag_start_event_args_8cs.html", "_controll_point_drag_start_event_args_8cs" ],
    [ "ControlPointDragEventArgs.cs", "_control_point_drag_event_args_8cs.html", "_control_point_drag_event_args_8cs" ],
    [ "D2D1CustomShaderEffectBase.cs", "_d2_d1_custom_shader_effect_base_8cs.html", "_d2_d1_custom_shader_effect_base_8cs" ],
    [ "D2D1CustomShaderEffectImplBase.cs", "_d2_d1_custom_shader_effect_impl_base_8cs.html", "_d2_d1_custom_shader_effect_impl_base_8cs" ],
    [ "DrawDescription.cs", "_draw_description_8cs.html", "_draw_description_8cs" ],
    [ "EffectDescription.cs", "_effect_description_8cs.html", "_effect_description_8cs" ],
    [ "FrameTime.cs", "_player_2_video_2_frame_time_8cs.html", "_player_2_video_2_frame_time_8cs" ],
    [ "IDrawable.cs", "_i_drawable_8cs.html", "_i_drawable_8cs" ],
    [ "InterpolationModeEx.cs", "_interpolation_mode_ex_8cs.html", "_interpolation_mode_ex_8cs" ],
    [ "IShapeSource.cs", "_i_shape_source_8cs.html", "_i_shape_source_8cs" ],
    [ "IShapeSource2.cs", "_i_shape_source2_8cs.html", "_i_shape_source2_8cs" ],
    [ "ITimelineSource.cs", "_i_timeline_source_8cs.html", "_i_timeline_source_8cs" ],
    [ "ITransitionSource.cs", "_i_transition_source_8cs.html", "_i_transition_source_8cs" ],
    [ "IVideoEffectProcessor.cs", "_i_video_effect_processor_8cs.html", "_i_video_effect_processor_8cs" ],
    [ "TachieDescription.cs", "_tachie_description_8cs.html", "_tachie_description_8cs" ],
    [ "TachieFaceDescription.cs", "_tachie_face_description_8cs.html", "_tachie_face_description_8cs" ],
    [ "TachieSourceDescription.cs", "_tachie_source_description_8cs.html", "_tachie_source_description_8cs" ],
    [ "TimelineItemSourceDescription.cs", "_timeline_item_source_description_8cs.html", "_timeline_item_source_description_8cs" ],
    [ "TimelineSourceDescription.cs", "_timeline_source_description_8cs.html", "_timeline_source_description_8cs" ],
    [ "TimelineSourceUsage.cs", "_timeline_source_usage_8cs.html", "_timeline_source_usage_8cs" ],
    [ "VideoController.cs", "_video_controller_8cs.html", "_video_controller_8cs" ],
    [ "VideoControllerPointConnection.cs", "_video_controller_point_connection_8cs.html", "_video_controller_point_connection_8cs" ],
    [ "VideoControllerPointShape.cs", "_video_controller_point_shape_8cs.html", "_video_controller_point_shape_8cs" ],
    [ "VideoEffectController.cs", "_video_effect_controller_8cs.html", "_video_effect_controller_8cs" ]
];