var namespace_yukkuri_movie_maker_1_1_plugin =
[
    [ "Brush", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_brush.html", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_brush" ],
    [ "Effects", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_effects.html", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_effects" ],
    [ "FileSource", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_file_source.html", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_file_source" ],
    [ "FileWriter", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_file_writer.html", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_file_writer" ],
    [ "Shape", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_shape.html", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_shape" ],
    [ "Tachie", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_tachie.html", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_tachie" ],
    [ "TextCompletion", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_text_completion.html", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_text_completion" ],
    [ "Transcription", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_transcription.html", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_transcription" ],
    [ "Transition", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_transition.html", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_transition" ],
    [ "Voice", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_voice.html", "namespace_yukkuri_movie_maker_1_1_plugin_1_1_voice" ],
    [ "AudioFileSourceFactory", "class_yukkuri_movie_maker_1_1_plugin_1_1_audio_file_source_factory.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_audio_file_source_factory" ],
    [ "CachedImageFileSource", "class_yukkuri_movie_maker_1_1_plugin_1_1_cached_image_file_source.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_cached_image_file_source" ],
    [ "CachedVideoFileSource", "class_yukkuri_movie_maker_1_1_plugin_1_1_cached_video_file_source.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_cached_video_file_source" ],
    [ "CacheProvider", "class_yukkuri_movie_maker_1_1_plugin_1_1_cache_provider.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_cache_provider" ],
    [ "EffectFactories", "class_yukkuri_movie_maker_1_1_plugin_1_1_effect_factories.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_effect_factories" ],
    [ "IEffectInfo", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_effect_info.html", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_effect_info" ],
    [ "IImageFileSource", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_image_file_source.html", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_image_file_source" ],
    [ "ILocalizePlugin", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_localize_plugin.html", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_localize_plugin" ],
    [ "ImageFileSource", "class_yukkuri_movie_maker_1_1_plugin_1_1_image_file_source.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_image_file_source" ],
    [ "ImageFileSourceFactory", "class_yukkuri_movie_maker_1_1_plugin_1_1_image_file_source_factory.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_image_file_source_factory" ],
    [ "IPlugin", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_plugin.html", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_plugin" ],
    [ "ISetting", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_setting.html", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_setting" ],
    [ "IToolPlugin", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_tool_plugin.html", "interface_yukkuri_movie_maker_1_1_plugin_1_1_i_tool_plugin" ],
    [ "PluginAssemblyLoader", "class_yukkuri_movie_maker_1_1_plugin_1_1_plugin_assembly_loader.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_plugin_assembly_loader" ],
    [ "PluginDetailsAttribute", "class_yukkuri_movie_maker_1_1_plugin_1_1_plugin_details_attribute.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_plugin_details_attribute" ],
    [ "PluginLoader", "class_yukkuri_movie_maker_1_1_plugin_1_1_plugin_loader.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_plugin_loader" ],
    [ "PluginLoaderSettings", "class_yukkuri_movie_maker_1_1_plugin_1_1_plugin_loader_settings.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_plugin_loader_settings" ],
    [ "SettingsBase< T >", "class_yukkuri_movie_maker_1_1_plugin_1_1_settings_base-1-g.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_settings_base-1-g" ],
    [ "ThemeManager", "class_yukkuri_movie_maker_1_1_plugin_1_1_theme_manager.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_theme_manager" ],
    [ "VideoEffectFactory", "class_yukkuri_movie_maker_1_1_plugin_1_1_video_effect_factory.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_video_effect_factory" ],
    [ "VideoEffectTemplateFactory", "class_yukkuri_movie_maker_1_1_plugin_1_1_video_effect_template_factory.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_video_effect_template_factory" ],
    [ "VideoFileSourceFactory", "class_yukkuri_movie_maker_1_1_plugin_1_1_video_file_source_factory.html", "class_yukkuri_movie_maker_1_1_plugin_1_1_video_file_source_factory" ],
    [ "SettingsCategory", "namespace_yukkuri_movie_maker_1_1_plugin.html#a1b8808edf20603ac7571d899dd5380f8", [
      [ "None", "namespace_yukkuri_movie_maker_1_1_plugin.html#a1b8808edf20603ac7571d899dd5380f8a6adf97f83acf6453d4a6a4b1070f3754", null ],
      [ "Voice", "namespace_yukkuri_movie_maker_1_1_plugin.html#a1b8808edf20603ac7571d899dd5380f8ad7a3fdf1351b72249a47454751549deb", null ]
    ] ]
];